[package]
name = "release_cover_art"
edition = "2024"
license = "Apache 2.0"
authors = ["Miso Labs, Inc. (build@miso.network)"]

[dependencies]
cover_art = { git = "https://github.com/misofm/cover-art.git", rev = "2208553bcb3649706ff1ef6ada9d683d65b2415c" }
musicos = { git = "https://github.com/misofm/musicos.git", rev = "f7a2be77ecc4429a1c5ff70800490b1946b1defb" }
per_track = { git = "https://github.com/misofm/per-track.git", rev = "cce620bf3dcd73de5e8c6e1baf09ec988c365e6e" }
ori = { git = "https://github.com/unconfirmedlabs/ori.git", rev = "367ed5fe92a8b62da02c1116537cf08d111e0789", subdir = "move", modes = ["test"] }
