[package]
name = "release_cover_art"
edition = "2024"
license = "Apache 2.0"
authors = ["Miso Labs, Inc. (build@miso.network)"]

[dependencies]
cover_art = { git = "https://github.com/misofm/cover-art.git", rev = "21fb2c04417fb0075d47f20c28149100e90af2cb" }
miso = { git = "https://github.com/misofm/protocol.git", rev = "09f0dc699a112c37d8da8a765596cc1ed623fe79" }
per_track = { git = "https://github.com/misofm/per-track.git", rev = "ca18ddc32b22d46190d0b3d4d93d31ab2a6f090a" }
