[package]
name = "release_dsp_link"
edition = "2024"
license = "Apache 2.0"
authors = ["Miso Labs, Inc. (build@miso.network)"]

[dependencies]
musicos = { git = "https://github.com/misofm/musicos.git", rev = "5d16455af2ff1ccaa80f86475fec95d95df41e06" }
per_track = { git = "https://github.com/misofm/per-track.git", rev = "af815dc907aae8ec476130fe2ab9782b9be74cce" }
