[package]
name = "release_dsp_link"
edition = "2024"
license = "Apache 2.0"
authors = ["Miso Labs, Inc. (build@miso.network)"]

[dependencies]
miso = { git = "https://github.com/misofm/protocol.git", rev = "ffa0e38b8ba4815d81de1076101ea37d2c71c623" }
per_track = { git = "https://github.com/misofm/per-track.git", rev = "5048c8fbd6f3b725bda5b1dd9dfcd31e3dde8b50" }
