[package]
name = "release_credits"
edition = "2024"
license = "Apache 2.0"
authors = ["Miso Labs, Inc. (build@miso.network)"]

[dependencies]
miso = { git = "https://github.com/misofm/protocol.git", rev = "ffa0e38b8ba4815d81de1076101ea37d2c71c623" }
partyos = { git = "https://github.com/misofm/party.git", rev = "72fa0c9c982166f51527d20846c2bc365b5c17f6", rename-from = "miso_party" }
miso_credit = { git = "https://github.com/misofm/credit.git", rev = "70cce6ed4246384067f891230584657987e8b380" }
